# Generated by Django 5.2.5 on 2025-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0003_aiadvisor_aiadvisorrecommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiadvisor',
            name='api_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiadvisor',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
