# Generated by Django 5.2.5 on 2025-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0004_alter_aiadvisor_api_endpoint_alter_aiadvisor_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiadvisor',
            name='advisor_type',
            field=models.CharField(choices=[('OPENAI_GPT', 'OpenAI GPT'), ('CLAUDE', 'Anthropic Claude'), ('GEMINI', 'Google Gemini'), ('PERPLEXITY', 'Perplexity AI'), ('FMP', 'Financial Modeling Prep'), ('FINNHUB', 'Finnhub'), ('CUSTOM', 'Custom AI Service')], max_length=20),
        ),
    ]
