# Generated by Django 5.2.5 on 2025-09-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0005_alter_aiadvisor_advisor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiadvisor',
            name='advisor_type',
            field=models.CharField(choices=[('OPENAI_GPT', 'OpenAI GPT'), ('CLAUDE', 'Anthropic Claude'), ('GEMINI', 'Google Gemini'), ('PERPLEXITY', 'Perplexity AI'), ('FMP', 'Financial Modeling Prep'), ('FINNHUB', 'Finnhub'), ('YAHOO_ENHANCED', 'Yahoo Finance Enhanced'), ('POLYGON', 'Polygon.io'), ('IEX_CLOUD', 'IEX Cloud'), ('CUSTOM', 'Custom AI Service')], max_length=20),
        ),
    ]
