# Generated by Django 5.2.5 on 2025-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0006_alter_aiadvisor_advisor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='analyst_rating_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='analyst_rating_hold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='analyst_rating_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='analyst_rating_strong_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='analyst_rating_strong_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='analyst_target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='fmp_grade',
            field=models.CharField(blank=True, help_text='FMP consensus grade (A+, A, B+, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='fmp_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='FMP numerical score', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Company logo URL from FMP API', null=True),
        ),
    ]
