# Generated by Django 5.2.5 on 2025-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0007_add_fmp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='USD', help_text='Trading currency (USD, EUR, GBP, CHF, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, help_text='Stock exchange (NYSE, LSE, SIX, etc.)', max_length=20),
        ),
    ]
