# Generated by Django 5.2.5 on 2025-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0008_stock_currency_stock_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='source_reference',
            field=models.CharField(blank=True, help_text='Reference to source (e.g., advisor name, recommendation ID)', max_length=200),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Trade'), ('AI_RECOMMENDATION', 'AI Recommendation'), ('SMART_ANALYSIS', 'Smart Analysis'), ('MARKET_SCREENING', 'Market Screening'), ('AUTOMATED_STRATEGY', 'Automated Strategy'), ('REBALANCING', 'Portfolio Rebalancing'), ('STOP_LOSS', 'Stop Loss Trigger'), ('TAKE_PROFIT', 'Take Profit Trigger')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiadvisor',
            name='advisor_type',
            field=models.CharField(choices=[('OPENAI_GPT', 'OpenAI GPT'), ('CLAUDE', 'Anthropic Claude'), ('GEMINI', 'Google Gemini'), ('PERPLEXITY', 'Perplexity AI'), ('FMP', 'Financial Modeling Prep'), ('FINNHUB', 'Finnhub'), ('YAHOO_ENHANCED', 'Yahoo Finance Enhanced'), ('POLYGON', 'Polygon.io'), ('IEX_CLOUD', 'IEX Cloud'), ('MARKET_SCREENING', 'Market Screening Service'), ('CUSTOM', 'Custom AI Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True, help_text='Detailed explanation of trade reasoning'),
        ),
    ]
