# Generated by Django 5.2.5 on 2025-09-24 13:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0010_riskprofile_smartanalysissession_smartrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='allow_penny_stocks',
            field=models.BooleanField(default=False, help_text='Allow penny stocks (price < $5) and micro-cap stocks (market cap < $100M) in recommendations'),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='min_market_cap',
            field=models.BigIntegerField(default=100000000, help_text='Minimum market cap threshold in USD (micro-cap filter)'),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='min_stock_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Minimum stock price threshold (penny stock filter)', max_digits=10),
        ),
    ]
