# Generated by Django 5.2.5 on 2025-10-03 10:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0011_add_penny_stock_risk_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='sell_hold_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Minimum adjusted confidence to consider HOLD as partial SELL', max_digits=3),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='sell_weight',
            field=models.IntegerField(default=5, help_text='Sell aggressiveness multiplier (1=conservative, 10=aggressive). Multiplies sell confidence scores.'),
        ),
    ]
