# Generated by Django 5.2.5 on 2025-10-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0012_add_sell_weight_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sell_weight',
            field=models.IntegerField(default=5, help_text='Portfolio-level sell aggressiveness (1=conservative, 10=aggressive). Overrides risk profile setting.'),
        ),
    ]
