# Generated by Django 5.2.5 on 2025-10-03 12:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0013_add_portfolio_sell_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='profit_taking_enabled',
            field=models.BooleanField(default=True, help_text='Enable automated profit-taking on volatile stocks with significant gains'),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='profit_taking_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum gain percentage to trigger profit-taking recommendation', max_digits=5),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='volatility_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Minimum annual volatility percentage to consider stock for profit-taking', max_digits=5),
        ),
    ]
