# Generated by Django 5.2.5 on 2025-10-09 13:12

from decimal import Decimal
from django.db import migrations, models


def convert_sellweight_values(apps, schema_editor):
    """Convert sell_weight from old 1-10 scale to new 0.33-3.0 scale"""
    Portfolio = apps.get_model('soulstrader', 'Portfolio')
    RiskProfile = apps.get_model('soulstrader', 'RiskProfile')
    
    # Mapping: old integer values to new decimal values
    conversion_map = {
        1: Decimal('0.33'), 2: Decimal('0.33'),  # Very Bullish
        3: Decimal('0.66'), 4: Decimal('0.66'),  # Bullish
        5: Decimal('1.00'), 6: Decimal('1.00'),  # Balanced
        7: Decimal('1.50'), 8: Decimal('1.50'),  # Bearish
        9: Decimal('3.00'), 10: Decimal('3.00'), # Very Bearish
    }
    
    # Convert Portfolio sell_weight values
    for portfolio in Portfolio.objects.all():
        old_value = int(portfolio.sell_weight) if portfolio.sell_weight else 5
        portfolio.sell_weight = conversion_map.get(old_value, Decimal('1.00'))
        portfolio.save(update_fields=['sell_weight'])
    
    # Convert RiskProfile sell_weight values
    for risk_profile in RiskProfile.objects.all():
        old_value = int(risk_profile.sell_weight) if risk_profile.sell_weight else 5
        risk_profile.sell_weight = conversion_map.get(old_value, Decimal('1.00'))
        risk_profile.save(update_fields=['sell_weight'])
    
    # Convert RiskProfile min_confidence_score from 0-1 scale to 0-9 scale
    # Old default was 0.70, new equivalent is about 2.0 (conservative estimate)
    for risk_profile in RiskProfile.objects.all():
        old_score = float(risk_profile.min_confidence_score)
        if old_score < 1.0:  # If it's on the old 0-1 scale
            # Scale up: multiply by ~3 (assuming max 6 advisors with strong multiplier)
            risk_profile.min_confidence_score = Decimal(str(old_score * 3))
            risk_profile.save(update_fields=['min_confidence_score'])
    
    # Convert RiskProfile sell_hold_threshold from 0-1 scale to 0-9 scale
    for risk_profile in RiskProfile.objects.all():
        old_threshold = float(risk_profile.sell_hold_threshold)
        if old_threshold < 1.0:  # If it's on the old 0-1 scale
            # Scale up: multiply by ~3
            risk_profile.sell_hold_threshold = Decimal(str(old_threshold * 3))
            risk_profile.save(update_fields=['sell_hold_threshold'])


def reverse_conversion(apps, schema_editor):
    """Reverse the conversion if migration is rolled back"""
    Portfolio = apps.get_model('soulstrader', 'Portfolio')
    RiskProfile = apps.get_model('soulstrader', 'RiskProfile')
    
    # Reverse mapping
    reverse_map = {
        Decimal('0.33'): 2,
        Decimal('0.66'): 4,
        Decimal('1.00'): 5,
        Decimal('1.50'): 7,
        Decimal('3.00'): 9,
    }
    
    for portfolio in Portfolio.objects.all():
        portfolio.sell_weight = reverse_map.get(portfolio.sell_weight, 5)
        portfolio.save(update_fields=['sell_weight'])
    
    for risk_profile in RiskProfile.objects.all():
        risk_profile.sell_weight = reverse_map.get(risk_profile.sell_weight, 5)
        # Scale confidence scores back down
        risk_profile.min_confidence_score = Decimal(str(float(risk_profile.min_confidence_score) / 3))
        risk_profile.sell_hold_threshold = Decimal(str(float(risk_profile.sell_hold_threshold) / 3))
        risk_profile.save(update_fields=['sell_weight', 'min_confidence_score', 'sell_hold_threshold'])


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0014_add_profit_taking_fields'),
    ]

    operations = [
        # First, alter the fields to allow decimals
        migrations.AlterField(
            model_name='portfolio',
            name='sell_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Market sentiment preference: 0.33=Very Bullish, 0.66=Bullish, 1.0=Balanced, 1.5=Bearish, 3.0=Very Bearish. Overrides risk profile setting.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='min_confidence_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Minimum confidence score threshold for recommendations (0-9 scale based on advisor consensus)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='sell_hold_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Minimum adjusted confidence to generate SELL recommendation (0-9 scale)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='sell_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Market sentiment preference: 0.33=Very Bullish, 0.66=Bullish, 1.0=Balanced, 1.5=Bearish, 3.0=Very Bearish', max_digits=4),
        ),
        # Then convert existing data
        migrations.RunPython(convert_sellweight_values, reverse_conversion),
    ]
