# Generated by Django 5.2.5 on 2025-10-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0015_update_sellweight_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='day_change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Day change percentage (increased to handle extreme moves like +10000%)', max_digits=8, null=True),
        ),
    ]
