# Generated by Django 5.2.5 on 2025-10-12 13:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulstrader', '0018_bank_allocation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='discovery_method',
            field=models.CharField(blank=True, help_text='Specific method used (most_active, undervalued_growth, top_gainers, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='discovery_source',
            field=models.CharField(blank=True, help_text='Source that discovered this stock (alpha_vantage, yahoo_finance, fmp, manual, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='min_confidence_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.60'), help_text='Minimum confidence score threshold for recommendations (0-1 scale based on average advisor consensus)', max_digits=5),
        ),
    ]
